const FETCH_CATEGORIE = 'app/CATEGORIE/FETCH_CATEGORIE'
export const FETCH_CATEGORIE_REQUEST = `${FETCH_CATEGORIE}_REQUEST`
export const FETCH_CATEGORIE_SUCCESS = `${FETCH_CATEGORIE}_SUCCESS`
export const FETCH_CATEGORIE_FAILURE = `${FETCH_CATEGORIE}_FAILURE`


const ADD_CATEGORIE = 'app/CATEGORIE/ADD_CATEGORIE'
export const ADD_CATEGORIE_REQUEST = `${ADD_CATEGORIE}_REQUEST`
export const ADD_CATEGORIE_SUCCESS = `${ADD_CATEGORIE}_SUCCESS`
export const ADD_CATEGORIE_FAILURE = `${ADD_CATEGORIE}_FAILURE`


const FETCH_PRODUIT = 'app/PRODUIT/FETCH_PRODUIT'
export const FETCH_PRODUIT_REQUEST = `${FETCH_PRODUIT}_REQUEST`
export const FETCH_PRODUIT_SUCCESS = `${FETCH_PRODUIT}_SUCCESS`
export const FETCH_PRODUIT_FAILURE = `${FETCH_PRODUIT}_FAILURE`


const ADD_PRODUIT = 'app/PRODUIT/ADD_PRODUIT'
export const ADD_PRODUIT_REQUEST = `${ADD_PRODUIT}_REQUEST`
export const ADD_PRODUIT_SUCCESS = `${ADD_PRODUIT}_SUCCESS`
export const ADD_PRODUIT_FAILURE = `${ADD_PRODUIT}_FAILURE`

const Update_PRODUIT = 'app/Update_PRODUIT/Update_PRODUIT'
export const Update_PRODUIT_REQUEST = `${Update_PRODUIT}_REQUEST`
export const Update_PRODUIT_SUCCESS = `${Update_PRODUIT}_SUCCESS`
export const Update_PRODUIT_FAILURE = `${Update_PRODUIT}_FAILURE`

const DELETE_PRODUIT = 'app/PRODUIT/DELETE_PRODUIT'
export const DELETE_PRODUIT_REQUEST = `${DELETE_PRODUIT}_REQUEST`

export const DELETE_PRODUIT_SUCCESS = `${DELETE_PRODUIT}_SUCCESS`
export const DELETE_PRODUIT_FAILURE = `${DELETE_PRODUIT}_FAILURE`

const SHERSH_PRODUIT = 'app/SHERSH_PRODUIT/SHERSH_PRODUIT'
export const SHERSH_PRODUIT_REQUEST = `${SHERSH_PRODUIT}_REQUEST`
export const SHERSH_PRODUIT_SUCCESS = `${SHERSH_PRODUIT}_SUCCESS`
export const SHERSH_PRODUIT_FAILURE = `${SHERSH_PRODUIT}_FAILURE`

const ADD_PANNIER = 'app/ADD_PANNIER/ADD_PANNIER'
export const ADD_PANNIER_REQUEST = `${ADD_PANNIER}_REQUEST`
export const ADD_PANNIER_SUCCESS = `${ADD_PANNIER}_SUCCESS`
export const ADD_PANNIER_FAILURE = `${ADD_PANNIER}_FAILURE`